export const DomainErrorCode = {
  APPLICANT_ALREADY_EXISTS: 'APPLICANT_ALREADY_EXISTS',
  APPLICANT_NOT_FOUND: 'APPLICANT_NOT_FOUND',
  APPLICANT_LINKED_TO_CASES: 'APPLICANT_LINKED_TO_CASES',
  INVALID_PASSPORT_EXPIRY: 'INVALID_PASSPORT_EXPIRY',

  CLIENT_NOT_FOUND: 'CLIENT_NOT_FOUND',
  CLIENT_HAS_DEPENDENTS: 'CLIENT_HAS_DEPENDENTS',

  PROVIDER_ROUTE_NOT_FOUND: 'PROVIDER_ROUTE_NOT_FOUND',
  PROVIDER_ROUTE_DISABLED: 'PROVIDER_ROUTE_DISABLED',

  BOOKING_CASE_NOT_FOUND: 'BOOKING_CASE_NOT_FOUND',
  BOOKING_CASE_NOT_DRAFT: 'BOOKING_CASE_NOT_DRAFT',
  BOOKING_CASE_NOT_READY: 'BOOKING_CASE_NOT_READY',

  APPLICANT_ALREADY_LINKED: 'APPLICANT_ALREADY_LINKED',
  INVALID_PRIMARY_APPLICANT: 'INVALID_PRIMARY_APPLICANT',
  INVALID_APPLICANT_POSITION: 'INVALID_APPLICANT_POSITION',

  DOMAIN_CONFLICT: 'DOMAIN_CONFLICT',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  PROVIDER_ADAPTER_UNAVAILABLE: 'PROVIDER_ADAPTER_UNAVAILABLE',
  ORCHESTRATION_INVARIANT_VIOLATION: 'ORCHESTRATION_INVARIANT_VIOLATION',
} as const;

export type DomainErrorCode = (typeof DomainErrorCode)[keyof typeof DomainErrorCode];
